[package]
name = "lndw-compiler"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
license = "GPL-3.0-or-later"

[dependencies]
chumsky = "0.10"
eframe = { version = "0.31.1", features = ["persistence"] }
rust-i18n = "3.1.5"
